//=========================================================
//File name    : lintsissue_agent_agent_driver.sv
//Author       : OpenAI_Codex
//Module name  : lintsissue_agent_agent_driver
//Discribution : lintsissue_agent_agent_driver : driver
//Date         : 2026-04-12
//=========================================================
`ifndef LINTSISSUE_AGENT_AGENT_DRIVER__SV
`define LINTSISSUE_AGENT_AGENT_DRIVER__SV

class lintsissue_agent_agent_driver  extends tcnt_driver_base#(virtual lintsissue_agent_agent_interface,lintsissue_agent_agent_cfg,lintsissue_agent_agent_xaction);

    `uvm_component_utils(lintsissue_agent_agent_driver)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern virtual task reset_phase(uvm_phase phase);
    extern task main_phase(uvm_phase phase);
    extern task send_pkt(lintsissue_agent_agent_xaction tr);
    extern task drive_idle(tcnt_dec_base::drv_mode_e drv_mode);
endclass:lintsissue_agent_agent_driver

function lintsissue_agent_agent_driver::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void lintsissue_agent_agent_driver::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task lintsissue_agent_agent_driver::reset_phase(uvm_phase phase);

    super.reset_phase(phase);
    phase.raise_objection(this);

    repeat(2) begin
        @this.vif.drv_mp.drv_cb;
        this.drive_idle(this.cfg.drv_mode);
    end
    wait(vif.rst_n == 1'b1);
    repeat(20) begin
        @this.vif.drv_mp.drv_cb;
        this.drive_idle(this.cfg.drv_mode);
    end

    phase.drop_objection(this);
endtask:reset_phase

task lintsissue_agent_agent_driver::main_phase(uvm_phase phase);
    super.main_phase(phase);
    //while(1) begin
    if(this.cfg.sqr_sw==tcnt_dec_base::ON && this.cfg.drv_sw==tcnt_dec_base::ON) begin
        while(1) begin
            seq_item_port.try_next_item(req);
            if(req!=null) begin
                repeat(req.pre_pkt_gap) begin
                    @this.vif.drv_mp.drv_cb;
                    this.drive_idle(this.cfg.drv_mode);
                end
                @this.vif.drv_mp.drv_cb;
                this.send_pkt(req);
                repeat(req.post_pkt_gap) begin
                    @this.vif.drv_mp.drv_cb;
                    this.drive_idle(this.cfg.drv_mode);
                end
                seq_item_port.item_done();
            end
            else begin
                @this.vif.drv_mp.drv_cb;
                this.drive_idle(this.cfg.drv_mode);
            end
        end
    end
    else if (this.cfg.drv_sw==tcnt_dec_base::ON) begin
        while(1) begin
            @this.vif.drv_mp.drv_cb;
            `uvm_fatal(get_type_name(), $sformatf("sqr_sw==OFF & drv_sw==ON, please give a driver send task!"))
            //send task
        end
    end
endtask:main_phase

task lintsissue_agent_agent_driver::send_pkt(lintsissue_agent_agent_xaction tr);
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= tr.io_ooo_to_mem_intIssue_6_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= tr.io_ooo_to_mem_intIssue_6_0_bits_fuType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_6_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_6_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= tr.io_ooo_to_mem_intIssue_5_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= tr.io_ooo_to_mem_intIssue_5_0_bits_fuType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_5_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_5_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= tr.io_ooo_to_mem_intIssue_4_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= tr.io_ooo_to_mem_intIssue_4_0_bits_fuType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_4_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_4_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= tr.io_ooo_to_mem_intIssue_4_0_bits_imm; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= tr.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= tr.io_ooo_to_mem_intIssue_4_0_bits_pdest; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= tr.io_ooo_to_mem_intIssue_4_0_bits_isRVC; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= tr.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= tr.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= tr.io_ooo_to_mem_intIssue_4_0_bits_ssid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= tr.io_ooo_to_mem_intIssue_3_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= tr.io_ooo_to_mem_intIssue_3_0_bits_fuType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_3_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_3_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= tr.io_ooo_to_mem_intIssue_3_0_bits_imm; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= tr.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= tr.io_ooo_to_mem_intIssue_3_0_bits_pdest; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= tr.io_ooo_to_mem_intIssue_3_0_bits_isRVC; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= tr.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= tr.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= tr.io_ooo_to_mem_intIssue_3_0_bits_ssid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= tr.io_ooo_to_mem_intIssue_2_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_2_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_2_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= tr.io_ooo_to_mem_intIssue_2_0_bits_imm; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= tr.io_ooo_to_mem_intIssue_2_0_bits_pdest; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= tr.io_ooo_to_mem_intIssue_2_0_bits_rfWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= tr.io_ooo_to_mem_intIssue_2_0_bits_fpWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= tr.io_ooo_to_mem_intIssue_2_0_bits_pc; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= tr.io_ooo_to_mem_intIssue_2_0_bits_isRVC; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= tr.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= tr.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= tr.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= tr.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= tr.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= tr.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= tr.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= tr.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= tr.io_ooo_to_mem_intIssue_1_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_1_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_1_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= tr.io_ooo_to_mem_intIssue_1_0_bits_imm; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= tr.io_ooo_to_mem_intIssue_1_0_bits_pdest; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= tr.io_ooo_to_mem_intIssue_1_0_bits_rfWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= tr.io_ooo_to_mem_intIssue_1_0_bits_fpWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= tr.io_ooo_to_mem_intIssue_1_0_bits_pc; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= tr.io_ooo_to_mem_intIssue_1_0_bits_isRVC; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= tr.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= tr.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= tr.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= tr.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= tr.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= tr.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= tr.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= tr.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= tr.io_ooo_to_mem_intIssue_0_0_valid; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= tr.io_ooo_to_mem_intIssue_0_0_bits_fuOpType; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= tr.io_ooo_to_mem_intIssue_0_0_bits_src_0; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= tr.io_ooo_to_mem_intIssue_0_0_bits_imm; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= tr.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= tr.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= tr.io_ooo_to_mem_intIssue_0_0_bits_pdest; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= tr.io_ooo_to_mem_intIssue_0_0_bits_rfWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= tr.io_ooo_to_mem_intIssue_0_0_bits_fpWen; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= tr.io_ooo_to_mem_intIssue_0_0_bits_pc; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= tr.io_ooo_to_mem_intIssue_0_0_bits_isRVC; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= tr.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= tr.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= tr.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= tr.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= tr.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= tr.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= tr.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= tr.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag; 
    vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= tr.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value; 

endtask:send_pkt

task lintsissue_agent_agent_driver::drive_idle(tcnt_dec_base::drv_mode_e drv_mode);

    if(drv_mode==tcnt_dec_base::DRV_0) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= '0;

    end
    else if(drv_mode==tcnt_dec_base::DRV_1) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= '1;

    end
    else if(drv_mode==tcnt_dec_base::DRV_X) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= 'x;

    end
    else if(drv_mode==tcnt_dec_base::DRV_RAND) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= $urandom;

    end
    else if(drv_mode==tcnt_dec_base::DRV_LST) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_imm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_pc <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value <= '0;

    end

endtask:drive_idle

`endif

